apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:f9DkwonTFD7/CgYEDdOCr44WwMY=,iv:l3Oce1LWgg5tHMeX4H1JBN+H0kfjSJ3i8G2eqi88vws=,tag:8Hz4/e2C0Pk1r5BeZYyheQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:g3M4l/en85H7qdFWFjEvuolWSWIL8Ai93AnA36gDX1jrVIMYCA==,iv:OmB/+9VDk9Yfd/jvGN7lnpygXG/Zh5yriHIJ5+nmU8g=,tag:QcMv/qOFyUkIKi7Karwo5g==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:O5k1hnUMzsrawGsKqxVu7DCQ,iv:CbdR1VojPmUzC/3OB4D0CEejveXufStZo1QDcDRhb+k=,tag:aqKle/WDICnBYG6QiZ7U1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c2hfg5qg42v3jstgnp2nyml38krwjwyuzm49le5mhacx476qdqaqyrd88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ2RFc044emFnanZJVy9r
            UWxSVXJRL0MvdXNMSGUyYmszeGV6aGdjZWhzCnBneHV5MWp2WmIzN3NLckxMa1cx
            ZHJNaTQ0R3lYYVduL2ZuREV5MENUN28KLS0tIHNSNTE2aTNvaExBMDA3UnluaDhX
            M0FTNVdxUzUvTWFndlpEVWhEYWtNQTQK7HH8alA7IpDZCDItfof+tGI9CtMn3B32
            GMdrpGMGTnucjK2JNOBdOKMxKZrduwL12oatMyJbmYqj7xhLsrcJqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-21T19:20:01Z"
    mac: ENC[AES256_GCM,data:oEVbnmC5VrV2iVCh7wG+5GVNBDWdXbWU0o8OmI8o7JzlTg5LbgeX8U702j9vqwL344SaTuISXBJkQQbOUXyfwIxiQnz5SxGvsM7h89sMURmq1FuoQWZahML0ruL3smtX0Y1iKpKleWmG0I73kcz+t3ZLNitWuKhSZu0jP+ou/OA=,iv:cb13mHTTNKo9Ntx78Edg7qEA7R4deE0hRqmdfNGW0eY=,tag:I82HRZDIXcyAhKLpHVYmhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
