---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1c2hfg5qg42v3jstgnp2nyml38krwjwyuzm49le5mhacx476qdqaqyrd88k
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1c2hfg5qg42v3jstgnp2nyml38krwjwyuzm49le5mhacx476qdqaqyrd88k
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1c2hfg5qg42v3jstgnp2nyml38krwjwyuzm49le5mhacx476qdqaqyrd88k
