---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Denver"
  KUBE_VIP_ADDR: "192.168.5.219"
  METALLB_LB_RANGE: "192.168.5.220-192.168.5.225"
  METALLB_K8S_GATEWAY_ADDR: "192.168.5.220"
  METALLB_INGRESS_ADDR: "192.168.5.221"
